
// Contêiner onde será exibida a lista (cards)
const secretarias = [
    //{ abreviacao: "GP", secretaria: "Gabinete do Prefeito", nome: "KATSU YONAMINE", cargo: "Secretário Municipal de Governo Interino", cpf: "927.188.418-34", texto: "Secretário Municipal de Governo Interino, por atribuição conferida através do artigo 22, inciso VIII" },
    
    //
    { abreviacao: "GP", secretaria: "Gabinete do Prefeito", nome: "KATSU YONAMINE", cargo: "SECRETÁRIO MUNICIPAL DO GABINETE DO PREFEITO", cpf: "927.188.418-34", texto: "titular do Gabinete do Prefeito" , extra:"" },
    { abreviacao: "GERAL DO GABINETE", secretaria: "Gabinete do Prefeito", nome: "REINALDO MOREIRA BRUNO", cargo: "Secretário Municipal Geral de Gabinete do Prefeito", cpf: "837.438.808-06", texto: "titular da Secretaria Geral de Gabinete do Prefeito" , extra:"" },
    { abreviacao: "SEG", secretaria: "Secretaria de Governo", nome: "ALEXANDRE GALLO RODRIGUES", cargo: "Secretário Municipal de Governo", cpf: "189.301.658-77", texto: "titular da Secretaria de Governo" , extra:"" },
    { abreviacao: "SEPLAN", secretaria: "Secretaria de Planejamento", nome: "JOSIE YABUTA DE LIMA HOLLANDA", cargo: "Secretária Municipal de Planejamento", cpf: "300.105.098-52", texto: "titular da Secretaria de Planejamento" , extra:"" },
    { abreviacao: "SEASP", secretaria: "Secretaria de Assuntos de Segurança Pública", nome: "MAURICIO VIEIRA IZUMI", cargo: "Secretário Municipal de Assuntos de Segurança Pública", cpf: "130.501.278-05", texto: "titular da Secretaria de Assuntos de Segurança Pública" , extra:"" },
    { abreviacao: "SEAD", secretaria: "Secretaria de Administração", nome: "RONALDO FERREIRA DE ALCÂNTARA", cargo: "Secretário Municipal de Administração Interino", cpf: "121.247.468-63", texto: "Secretário Municipal de Administração Interino" , extra:"" },
    { abreviacao: "PROGEM", secretaria: "Procuradoria Geral do Município", nome: "GLAUCIA ANTUNES ALVAREZ", cargo: "Procuradora Geral do Município", cpf: "133.887.368-71", texto: "titular da Procuradoria Geral do Município" , extra:"" },
    { abreviacao: "SEFIN", secretaria: "Secretaria de Finanças", nome: "CRISTIANO DE MOLA", cargo: "Secretário Municipal de Finanças", cpf: "291.045.598-00", texto: "titular da Secretaria de Finanças" , extra:"" },
    { abreviacao: "SEAS", secretaria: "Secretaria de Assistência Social", nome: "GISELE DOMINGUES", cargo: "Secretária Municipal de Assistência Social", cpf: "091.127.228-39", texto: "titular da Secretaria de Assistência Social" , extra:"" },
    { abreviacao: "SEDUC", secretaria: "Secretaria de Educação", nome: "PATRICIA CONCEIÇÃO ALMEIDA DIAS", cargo: "Secretária Municipal de Educação", cpf: "199.354.948-02", texto: "titular da Secretaria de Educação" , extra:"" },
    { abreviacao: "SESAP", secretaria: "Secretaria de Saúde Pública", nome: "JOSÉ ISAIAS COSTA LIMA", cargo: "Secretário Municipal de Saúde Pública", cpf: "318.588.378-04", texto: "titular da Secretaria de Saúde Pública" , extra:"" },
    { abreviacao: "SEURB", secretaria: "Secretaria de Urbanismo", nome: "LUÍS FERNANDO FÉLIX DE PAULA", cargo: "Secretário Municipal de Urbanismo", cpf: "133.741.818-80", texto: "titular da Secretaria de Urbanismo" , extra:"" },
    { abreviacao: "SEMA", secretaria: "Secretaria de Meio Ambiente", nome: "VALDIR PEREIRA RAMOS FILHO", cargo: "Secretário Municipal de Meio Ambiente", cpf: "312.019.218-05", texto: "titular da Secretaria de Meio Ambiente" , extra:"" },
    { abreviacao: "SEOP", secretaria: "Secretaria de Obras Públicas", nome: "ELOISA OJEA GOMES TAVARES", cargo: "Secretária Municipal de Obras Públicas", cpf: "080.557.808-03", texto: "titular da Secretaria de Obras Públicas" , extra:"" },
    { abreviacao: "SEHAB", secretaria: "Secretaria de Habitação", nome: "FABRÍCIO MENEZES DE PAULA", cargo: "Secretário Municipal de Habitação", cpf: "270.442.408-01", texto: "titular da Secretaria de Habitação" , extra:"" },
    { abreviacao: "SESURB", secretaria: "Secretaria de Serviços Urbanos", nome: "SORAIA M. MILAN", cargo: "Secretária Municipal de Serviços Urbanos", cpf: "134.045.568-44", texto: "titular da Secretaria de Serviços Urbanos" , extra:"" },
    { abreviacao: "SETRAN", secretaria: "Secretaria de Trânsito", nome: "MARCELINO SANTOS GOMES", cargo: "Secretário Municipal de Trânsito", cpf: "169.600.188-97", texto: "titular da Secretaria de Trânsito", extra:"" },
    { abreviacao: "SETRANSP", secretaria: "Secretaria de Transportes", nome: "LEANDRO AVELINO RODRIGUES CRUZ", cargo: "Secretário Municipal de Transportes", cpf: "266.208.828-11", texto: "titular da Secretaria de Transportes" , extra:"" },
    { abreviacao: "SEAI", secretaria: "Secretaria de Assuntos Institucionais", nome: "JOÃO ALVES CORREA NETO", cargo: "Secretário Municipal de Assuntos Institucionais", cpf: "288.643.208-30", texto: "titular da Secretaria de Assuntos Institucionais" , extra:"" },
    { abreviacao: "SECTUR", secretaria: "Secretaria de Cultura e Turismo", nome: "MAURÍCIO DA SILVA PETIZ", cargo: "Secretário Municipal de Cultura e Turismo", cpf: "032.164.678-99", texto: "titular da Secretaria de Cultura e Turismo" , extra:"" },
    { abreviacao: "SEEL", secretaria: "Secretaria de Esporte e Lazer", nome: "RODRIGO SANTANA", cargo: "Secretário Municipal de Esporte e Lazer", cpf: "287.067.718-90", texto: "titular da Secretaria de Esporte e Lazer" , extra:"" },
    { abreviacao: "SEDI", secretaria: "Secretaria de Diversidade e Inclusão", nome: "VERA LUCIA FIGUEIREDO BENICIO", cargo: "Secretária Municipal de Diversidade e Inclusão", cpf: "018.104.628-86", texto: "titular da Secretaria de Diversidade e Inclusão Social" , extra:"" },
    { abreviacao: "SEPEE", secretaria: "Secretaria de Projetos Especiais e Estratégicos", nome: "APARECIDA REGINA FERMINO DA SILVA", cargo: "Secretária Municipal de Projetos Especiais e Estratégicos Interina", cpf: "045.334.268-08", texto: "titular da Secretaria Municipal de Projetos Especiais e Estratégicos Interino" , extra:"" },
    { abreviacao: "SUBS. DE AÇÕES DE CIDADANIA", secretaria: "Secretaria de Ações da Cidadania", nome: "CLAUDINO PACHECO FILHO", cargo: "Subsecretário de Ações da Cidadania", cpf: "058.198.678-40", texto: "titular da Subsecretaria de Ações da Cidadania" , extra:"" },
    { abreviacao: "SUBS. DE ASSUNTOS DA JUVENTUDE", secretaria: "Secretaria de Assuntos da Juventude", nome: "AUGUSTO ALEXANDRE VARGAS CAMARGO SCHELL", cargo: "Subsecretário Municipal de Assuntos da Juventude", cpf: "345.773.568-99", texto: "titular da Subsecretaria de Assuntos da Juventude" , extra:"" },
    { abreviacao: "GERAL DO GABINETE", secretaria: "Secretaria de Administração Geral do Gabinete", nome: "MARIA CAROLINA DONDON SALUM SILVEIRA", cargo: "Subsecretária de Administração da Secretaria Geral do Gabinete", cpf: "277.322.348-98", texto: "titular da Subsecretaria de Administração da Secretaria Geral do Gabinete", extra:"Adm." },
    { abreviacao: "SUBS. DE CONTROLE INTERNO", secretaria: "Secretaria de Controle Interno", nome: "ERIKA CRISTINA PICOLO", cargo: "Subsecretária de Controle Interno", cpf: "263.615.478-76", texto: "titular da Subsecretaria de Controle Interno", extra:"" },
    { abreviacao: "SUBS. DE COMUNICACAO SOCIAL", secretaria: "Secretaria de Comunicação Social", nome: "PAOLA KRISTINA VIEIRA DA SILVA", cargo: "Subsecretária de Comunicação Social", cpf: "293.484.018-23", texto: "titular da Subsecretaria de Comunicação Social" , extra:"" },
    { abreviacao: "SUBS. DE PLANEJAMENTO DE EXPANSÃO DA REDE ESCOLAR", secretaria: "Subsecretaria de Expansão de Planejamento de Rede Escolar", nome: "DENYS DOS SANTOS FONSECA", cargo: "Subsecretário de Expansão de Planejamento de Rede Escolar", cpf: "927.188.418-34", texto: "titular da Subsecretaria de Expansão de Planejamento de Rede Escolar", extra:"" }
];