
// Contêiner onde será exibida a lista (cards)
const secretarias = [
    //{ abreviacao: "GP", secretaria: "Gabinete do Prefeito", nome: "KATSU YONAMINE", cargo: "Secretário Municipal de Governo Interino", cpf: "927.188.418-34", texto: "Secretário Municipal de Governo Interino, por atribuição conferida através do artigo 22, inciso VIII" },
    //{ abreviacao: "Subsecretaria SEDUC", secretaria: "Subsecretaria de Expansão de Planejamento de Rede Escolar", nome: "DENYS DOS SANTOS FONSECA", cargo: "Subsecretário de Expansão de Planejamento de Rede Escolar", cpf: "927.188.418-34", texto: "Subsecretário de Expansão de Planejamento de Rede Escolar, por atribuição conferida através do artigo 19" },
    //
    { abreviacao: "GP", secretaria: "Gabinete do Prefeito", nome: "REINALDO MOREIRA BRUNO", cargo: "Secretário Municipal Geral de Gabinete do Prefeito", cpf: "837.438.808-06", texto: "titular da Secretaria Geral de Gabinete do Prefeito, por atribuição conferida através do artigo 12-A" },
    { abreviacao: "SEG", secretaria: "Secretaria de Governo", nome: "ALEXANDRE GALLO RODRIGUES", cargo: "Secretário Municipal de Governo", cpf: "189.301.658-77", texto: "Secretário Municipal de Governo, por atribuição conferida através do artigo 22, inciso VIII" },
    { abreviacao: "SEPLAN", secretaria: "Secretaria de Planejamento", nome: "JOSIE YABUTA DE LIMA HOLLANDA", cargo: "Secretária Municipal de Planejamento", cpf: "300.105.098-52", texto: "titular da Secretaria de Planejamento, por atribuição conferida através do artigo 25, inciso XV" },
    { abreviacao: "SEASP", secretaria: "Secretaria de Assuntos de Segurança Pública", nome: "MAURICIO VIEIRA IZUMI", cargo: "Secretário Municipal de Assuntos de Segurança Pública", cpf: "130.501.278-05", texto: "titular da Secretaria de Assuntos de Segurança Pública, por atribuição conferida através do artigo 28, inciso XIII" },
    { abreviacao: "SEAD", secretaria: "Secretaria de Administração", nome: "RONALDO FERREIRA DE ALCÂNTARA", cargo: "Secretário Municipal de Administração Interino", cpf: "121.247.468-63", texto: "Secretário Municipal de Administração Interino, por atribuição conferida através do inciso XVIII do artigo 31" },
    { abreviacao: "PROGEM", secretaria: "Procuradoria Geral do Município", nome: "GLAUCIA ANTUNES ALVAREZ", cargo: "Procuradora Geral do Município", cpf: "133.887.368-71", texto: "titular da Procuradoria Geral do Município, por atribuição conferida através do artigo 34, inciso XIX" },
    { abreviacao: "SEFIN", secretaria: "Secretaria de Finanças", nome: "CRISTIANO DE MOLA", cargo: "Secretário Municipal de Finanças", cpf: "291.045.598-00", texto: "titular da Secretaria de Finanças, por atribuição conferida através do artigo 40, inciso XX" },
    { abreviacao: "SEAS", secretaria: "Secretaria de Assistência Social", nome: "GISELE DOMINGUES", cargo: "Secretária Municipal de Assistência Social", cpf: "091.127.228-39", texto: "titular da Secretaria de Assistência Social, por atribuição conferida através do artigo 45, inciso IV" },
    { abreviacao: "SEDUC", secretaria: "Secretaria de Educação", nome: "PATRICIA CONCEIÇÃO ALMEIDA DIAS", cargo: "Secretária Municipal de Educação", cpf: "199.354.948-02", texto: "titular da Secretaria de Educação, por atribuição conferida através do artigo 48, inciso XXXI" },
    { abreviacao: "SESAP", secretaria: "Secretaria de Saúde Pública", nome: "JOSÉ ISAIAS COSTA LIMA", cargo: "Secretário Municipal de Saúde Pública", cpf: "318.588.378-04", texto: "titular da Secretaria de Saúde Pública, por atribuição conferida através do artigo 51, inciso XIX" },
    { abreviacao: "SEURB", secretaria: "Secretaria de Urbanismo", nome: "LUÍS FERNANDO FÉLIX DE PAULA", cargo: "Secretário Municipal de Urbanismo", cpf: "133.741.818-80", texto: "titular da Secretaria de Urbanismo, por atribuição conferida através do artigo 54, inciso X" },
    { abreviacao: "SEMA", secretaria: "Secretaria de Meio Ambiente", nome: "VALDIR PEREIRA RAMOS FILHO", cargo: "Secretário Municipal de Meio Ambiente", cpf: "312.019.218-05", texto: "titular da Secretaria de Meio Ambiente, por atribuição conferida através do artigo 57, inciso IV" },
    { abreviacao: "SEOP", secretaria: "Secretaria de Obras Públicas", nome: "ELOISA OJEA GOMES TAVARES", cargo: "Secretária Municipal de Obras Públicas", cpf: "080.557.808-03", texto: "titular da Secretaria de Obras Públicas, por atribuição conferida através do artigo 60, inciso XII" },
    { abreviacao: "SEHAB", secretaria: "Secretaria de Habitação", nome: "FABRÍCIO MENEZES DE PAULA", cargo: "Secretário Municipal de Habitação", cpf: "270.442.408-01", texto: "titular da Secretaria de Habitação, por atribuição conferida através do artigo 63, inciso V" },
    { abreviacao: "SESURB", secretaria: "Secretaria de Serviços Urbanos", nome: "SORAIA MOURãO MILAN", cargo: "Secretária Municipal de Serviços Urbanos", cpf: "134.045.568-44", texto: "titular da Secretaria de Serviços Urbanos, por atribuição conferida através do artigo 66, inciso XII" },
    { abreviacao: "SETRAN", secretaria: "Secretaria de Trânsito", nome: "MARCELINO SANTOS GOMES", cargo: "Secretário Municipal de Trânsito", cpf: "169.600.188-97", texto: "titular da Secretaria de Trânsito, por atribuição conferida através do artigo 69, inciso XXX" },
    { abreviacao: "SETRANSP", secretaria: "Secretaria de Transportes", nome: "LEANDRO AVELINO RODRIGUES CRUZ", cargo: "Secretário Municipal de Transportes", cpf: "266.208.828-11", texto: "titular da Secretaria de Transportes, por atribuição conferida através do artigo 72, inciso V" },
    { abreviacao: "SEAI", secretaria: "Secretaria de Assuntos Institucionais", nome: "JOÃO ALVES CORREA NETO", cargo: "Secretário Municipal de Assuntos Institucionais", cpf: "288.643.208-30", texto: "titular da Secretaria de Assuntos Institucionais, por atribuição conferida através do artigo 75, inciso VI" },
    { abreviacao: "SECTUR", secretaria: "Secretaria de Cultura e Turismo", nome: "MAURÍCIO DA SILVA PETIZ", cargo: "Secretário Municipal de Cultura e Turismo", cpf: "032.164.678-99", texto: "titular da Secretaria de Cultura e Turismo, por atribuição conferida através do artigo 78, inciso XXXVII" },
    { abreviacao: "SEEL", secretaria: "Secretaria de Esporte e Lazer", nome: "RODRIGO SANTANA", cargo: "Secretário Municipal de Esporte e Lazer", cpf: "287.067.718-90", texto: "titular da Secretaria de Esporte e Lazer, por atribuição conferida através do artigo 81, inciso XXVI" },
    { abreviacao: "SEDI", secretaria: "Secretaria de Diversidade e Inclusão", nome: "VERA LUCIA FIGUEIREDO BENICIO", cargo: "Secretária Municipal de Diversidade e Inclusão", cpf: "018.104.628-86", texto: "titular da Secretaria de Diversidade e Inclusão Social, por atribuição conferida através do artigo 82, inciso XIV" },
    { abreviacao: "SEPEE", secretaria: "Secretaria de Projetos Especiais e Estratégicos", nome: "APARECIDA REGINA FERMINO DA SILVA", cargo: "Secretária Municipal de Projetos Especiais e Estratégicos Interina", cpf: "045.334.268-08", texto: "Secretária Municipal de Projetos Especiais e Estratégicos Interino, por atribuição conferida através do inciso XII do artigo 82 B" },
    { abreviacao: "Ações da Cidadania", secretaria: "Secretaria de Ações da Cidadania", nome: "CLAUDINO PACHECO FILHO", cargo: "Subsecretário de Ações da Cidadania", cpf: "058.198.678-40", texto: "titular da Subsecretaria de Ações da Cidadania, por atribuição conferida através do artigo 19" },
    { abreviacao: "Assuntos da Juventude", secretaria: "Secretaria de Assuntos da Juventude", nome: "AUGUSTO ALEXANDRE VARGAS CAMARGO SCHELL", cargo: "Subsecretário Municipal de Assuntos da Juventude", cpf: "345.773.568-99", texto: "titular da Subsecretaria de Assuntos da Juventude, por atribuição conferida através do artigo 19" },
    { abreviacao: "Adm Geral do Gabinete", secretaria: "Secretaria de Administração Geral do Gabinete", nome: "MARIA CAROLINA DONDON SALUM SILVEIRA", cargo: "Subsecretária de Administração da Secretaria Geral do Gabinete", cpf: "277.322.348-98", texto: "titular da Subsecretaria de Administração da Secretaria Geral do Gabinete, por atribuição conferida através do artigo 19" },
    { abreviacao: "Controle Interno", secretaria: "Secretaria de Controle Interno", nome: "ERIKA CRISTINA PICOLO", cargo: "Subsecretária de Controle Interno", cpf: "263.615.478-76", texto: "titular da Subsecretaria de Controle Interno, por atribuição conferida através do artigo 14" },
    { abreviacao: "Comunicação Social", secretaria: "Secretaria de Comunicação Social", nome: "PAOLA KRISTINA VIEIRA DA SILVA", cargo: "Subsecretária de Comunicação Social", cpf: "293.464.018-23", texto: "titular da Subsecretaria de Comunicação Social, por atribuição conferida através do artigo 19" }
];